USE [master]
GO

/****** Object:  Database [bookstoreA]    Script Date: 14/8/2020 4:06:47 μμ ******/
CREATE DATABASE [bookstoreA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bookstoreA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\bookstoreA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bookstoreA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\bookstoreA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bookstoreA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bookstoreA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bookstoreA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bookstoreA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bookstoreA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bookstoreA] SET ARITHABORT OFF 
GO

ALTER DATABASE [bookstoreA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bookstoreA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bookstoreA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bookstoreA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bookstoreA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bookstoreA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bookstoreA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bookstoreA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bookstoreA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bookstoreA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bookstoreA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bookstoreA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bookstoreA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bookstoreA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bookstoreA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bookstoreA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bookstoreA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bookstoreA] SET RECOVERY FULL 
GO

ALTER DATABASE [bookstoreA] SET  MULTI_USER 
GO

ALTER DATABASE [bookstoreA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bookstoreA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bookstoreA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bookstoreA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bookstoreA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bookstoreA] SET  READ_WRITE 
GO


